### ISSUE TITLE
reactotoron needs to stay open

### ISSUE THREAD

**Issue by sagivYad2** [hsndmr/reactotron-react-query#1]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
app crashes if Reactotron is not open and connected
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by hsndmr** [comment]
Thanks for reporting. I will check and look into the matter further.

**Comment by MayheMatan** [comment]
+1

**Comment by chanphiromsok** [comment]
<img width="593" alt="image" src="https://github.com/hsndmr/reactotron-react-query/assets/65760336/f2407172-2471-420d-b079-c0111299b8cc">
 data is always undefined (I'm using v4 react query)

**Comment by hsndmr** [comment]
@chanphiromsok 
Your status is currently loading. Could you please check it once the status indicates success? Thank you.
