### ISSUE TITLE
documentation unclear for first time

### ISSUE THREAD

**Issue by tyeetale** [hsndmr/reactotron-react-query#2]
# **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x ] question about how to use this project

# **Summary**

I'm a first-time user transitioning from the @tanstack/react-query documentation and installing via Reactotron. I've noticed that the default installation on Reactotron uses an asynchronous manager setup as follows:

```tsx

import Reactotron from "reactotron-react-native";
import { AsyncStorage } from "@react-native-async-storage/async-storage";

Reactotron.setAsyncStorageHandler(AsyncStorage)
  .configure() // controls connection & communication settings
  .useReactNative() // add all built-in react native plugins
  .connect(); // let's connect!
```

However, I've also noted that React Query has been updated. Nevertheless, the current documentation refers to just `react-query` instead of `@tanstack/react-query`. Furthermore, the provided code snippet is causing confusion:

```tsx

Reactotron.use(reactotronReactQuery(queryClientManager))
  .configure({
    onDisconnect: () => {
      queryClientManager.unsubscribe();
    },
  })
  .useReactNative()
  .connect();
 ```
 
This results in an error message stating:

```
Argument of type '(reactotron: ReactotronCore) => { onCommand: ({ type, payload }: { type: string; payload?: any; }) => void; }' is not assignable to parameter of type 'PluginCreator<ReactotronReactNative>'.
  Types of parameters 'reactotron' and 'client' are incompatible.
    Type 'ReactotronReactNative' is not assignable to type 'ReactotronCore'.
      Types of property 'options' are incompatible.
        Type 'ClientOptions<ReactotronReactNative>' is not assignable to type 'ClientOptions<ReactotronCore>'.
          Type 'ReactotronCore' is missing the following properties from type 'ReactotronReactNative': useReactNative, setAsyncStorageHandler, log, logImportant, and 15 more.
```

Could you please provide clarification on:

- The availability of updated documentation that corresponds with the @tanstack/react-query package.
- The current maintenance status of the project.

Thank you for your assistance.

# **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Resources used:
- https://docs.infinite.red/reactotron/quick-start/react-native/
- https://tanstack.com/query/latest/docs/framework/react/react-native

**Comment by hsndmr** [comment]
@tyeetale you can use with @tanstack/react-query. I will update documentation this month.

**Comment by hsndmr** [comment]
@tyeetale i updated readme and i added custom command to invalidate queries.

**Comment by hsndmr** [comment]
@tyeetale i updated readme and i added custom command to invalidate queries.
